# Generated by Django 2.2.5 on 2020-01-23 08:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('content', '0001_initial'),
        ('account', '0002_auto_20200123_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='default_pic/city.png', null=True, upload_to='pictures/city')),
                ('name', models.CharField(max_length=64, verbose_name='City name')),
                ('articles', models.ManyToManyField(blank=True, to='content.Article')),
                ('organizations', models.ManyToManyField(blank=True, to='organization.Organization')),
                ('profiles', models.ManyToManyField(blank=True, to='account.Profile')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='default_pic/country.png', null=True, upload_to='pictures/country')),
                ('name', models.CharField(max_length=64, verbose_name='Country name')),
                ('ISO_3166_1', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='ISO 3166-1')),
                ('cities', models.ManyToManyField(blank=True, to='location.City')),
                ('organizations', models.ManyToManyField(blank=True, to='organization.Organization')),
                ('profiles', models.ManyToManyField(blank=True, to='account.Profile')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
            },
        ),
    ]
