# Generated by Django 2.2.5 on 2020-01-23 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Category name')),
                ('question', models.CharField(max_length=240, verbose_name='Question')),
                ('positive_answer', models.CharField(max_length=64, verbose_name='Positive answer')),
                ('indefinite_answer', models.CharField(max_length=64, verbose_name='indefinite answer')),
                ('negative_answer', models.CharField(max_length=64, verbose_name='Negative answer')),
            ],
            options={
                'verbose_name': 'Rating Category',
                'verbose_name_plural': 'Rating Category',
            },
        ),
        migrations.CreateModel(
            name='FlexibleScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=240, null=True, verbose_name='Question')),
                ('positive_answer', models.CharField(max_length=64, verbose_name='Positive answer')),
                ('indefinite_answer', models.CharField(max_length=64, verbose_name='indefinite answer')),
                ('negative_answer', models.CharField(max_length=64, verbose_name='Negative answer')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rating.RatingCategory', verbose_name='Rate category')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Content type')),
                ('indefinite', models.ManyToManyField(blank=True, related_name='indef_r', to=settings.AUTH_USER_MODEL, verbose_name='indefinite reactions')),
                ('negative', models.ManyToManyField(blank=True, related_name='ngtv_r', to=settings.AUTH_USER_MODEL, verbose_name='Negative reactions')),
                ('positive', models.ManyToManyField(blank=True, related_name='pstv_r', to=settings.AUTH_USER_MODEL, verbose_name='Positive reactions')),
            ],
            options={
                'verbose_name': 'Flexible Scale',
                'verbose_name_plural': 'Flexible Scales',
            },
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Content type')),
                ('down', models.ManyToManyField(blank=True, related_name='down', to=settings.AUTH_USER_MODEL, verbose_name='Down content')),
                ('up', models.ManyToManyField(blank=True, related_name='up', to=settings.AUTH_USER_MODEL, verbose_name='Up content')),
            ],
            options={
                'verbose_name': 'Content rating',
                'verbose_name_plural': 'Content ratings',
            },
        ),
    ]
