# Generated by Django 2.2.5 on 2020-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblescale',
            name='indefinite_answer',
            field=models.CharField(blank=True, max_length=64, verbose_name='indefinite answer'),
        ),
        migrations.AlterField(
            model_name='flexiblescale',
            name='negative_answer',
            field=models.CharField(blank=True, max_length=64, verbose_name='Negative answer'),
        ),
        migrations.AlterField(
            model_name='flexiblescale',
            name='positive_answer',
            field=models.CharField(blank=True, max_length=64, verbose_name='Positive answer'),
        ),
        migrations.AlterField(
            model_name='flexiblescale',
            name='question',
            field=models.CharField(blank=True, max_length=240, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='indefinite_answer',
            field=models.CharField(blank=True, max_length=64, verbose_name='indefinite answer'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='negative_answer',
            field=models.CharField(blank=True, max_length=64, verbose_name='Negative answer'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='positive_answer',
            field=models.CharField(blank=True, max_length=64, verbose_name='Positive answer'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='question',
            field=models.CharField(blank=True, max_length=240, verbose_name='Question'),
        ),
    ]
