# Generated by Django 2.2.5 on 2020-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200212_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblescale',
            name='question',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='question',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Question'),
        ),
    ]
